lite-lava-dispatcher/Dockerfile: Don't check cert when downloading JLink.
Because:

--2020-02-11 18:03:13--  https://www.segger.com/downloads/jlink/JLink_Linux_V650_x86_64.deb
Resolving www.segger.com (www.segger.com)... 78.31.67.95
Connecting to www.segger.com (www.segger.com)|78.31.67.95|:443... connected.
ERROR: cannot verify www.segger.com's certificate, issued by ‘CN=AlphaSSL CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
  Unable to locally verify the issuer's authority.
To connect to www.segger.com insecurely, use `--no-check-certificate'.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>